artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/KLTsai/Branching-storage/raw/refs/heads/master/samsung-corpus.7z
  local_data_file: artifacts/data_ingestion/data.7z
  unzip_dir: artifacts/data_ingestion

data_embedding:
  root_dir: artifacts/data_embedding
  data_path: artifacts/data_ingestion
  model_name: ibm-granite/granite-embedding-278m-multilingual
  text_column: dialogue

vector_storage:
  data_path: artifacts/data_embedding/samsum_dataset
  embedding_dim: 768

gemini: 
  # Gemini API 設定
  # api-key store in .env
  gemini_model: gemini-2.0-flash-001
  gemini_temperature: 0.3
  gemini_max_output_tokens: 512

RAG_system:
  max_retrieval_docs: 10